baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "texify2"
enableRobotsTXT = true
hasCJKLanguage = true
paginate = 5
rssLimit = 10


[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark.renderer]
unsafe= true
[markup.highlight]
guessSyntax = false
hl_Lines = ''
lineAnchors = ''
lineNoStart = 1
# 显示每一行代码前的序号
lineNos = true
anchorLineNos = false
lineNumbersInTable = true
noClasses = false
noHl = false
hl_inline = false
# 代码高亮样式，更多样式请移步：https://xyproto.github.io/splash/docs/
style = 'algol'
tabWidth = 2
[markup.tableOfContents]
  endLevel = 6
  ordered = false
  startLevel = 2
[markup.goldmark]
[markup.goldmark.extensions]
[markup.goldmark.extensions.passthrough]
    enable = true
[markup.goldmark.extensions.passthrough.delimiters]
    block = [['\[', '\]'], ['$$', '$$']]
    inline = [['\(', '\)'], ['$', '$']]

# enable the following code if there are html statements in your md file
# 如果md文件中有html语句，请启用以下代码
# [markup.goldmark]
#     [markup.goldmark.renderer]
#         unsafe = true
  
# Syntax highligth on code blocks

[module]
  [module.hugoVersion]
    min = "0.113.0"

[[menu.main]]
identifier = "guid"
name = "Guid"
url = "../"
weight = 1
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 2
[[menu.main]]
identifier = "post"
name = "Posts"
url = "/post/"
weight = 3
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 6

[taxonomies]
tags = "tags"
categories = "categories"

[params]
numberedSubtitles = true
toc = true

[params.commentEngine]
code = """
<script src="https://giscus.app/client.js"
        data-repo="weastur/hugo-texify2"
        data-repo-id="R_kgDOJwiYnA"
        data-category="Comments"
        data-category-id="DIC_kwDOJwiYnM4CXVgQ"
        data-mapping="title"
        data-strict="1"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="top"
        data-theme="light"
        data-lang="en"
        data-loading="lazy"
        crossorigin="anonymous"
        async>
</script>
"""

[params.buymeacoffee]
code = """
<script data-name="BMC-Widget" data-cfasync="false" src="https://cdnjs.buymeacoffee.com/1.0.0/widget.prod.min.js" data-id="weastur" data-description="Support me on Buy me a coffee!" data-message="" data-color="#FF5F5F" data-position="Right" data-x_margin="18" data-y_margin="18"></script>
"""
title="TeXify2"
description = "TeXify2 - a minimal, latex-style hugo theme for personal blogging"
images = ['images/logo.jpg']
footnote = """
Follow me on <a class=link href=https://github.com/Luo25177 target=_blank rel=noopener>GitHub</a>,
<a class=link href=https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en target=_blank rel=noopener>CC BY-NC-SA 4.0</a>
"""
keywords = ["hugo", "latex", "theme", "blog", "texify", "texify2", "weastur"]
customCSS = []
customJS = []
dateFormat = "January 2, 2006"
emphasisWithDots = true
since = "2024"
toc = false
showWordCount = true
showReadingTime = true
rootFontSize = "120%"
math = true
enableDuckDuckGoSearchBox = true
numberedSubtitles = false

[params.sharingbuttons]
facebook = true
twitter = true
email = true
linkedin = true
reddit = true
whatsapp = true
hackernews = true
telegram = true

[author]
email = "me@weastur.com"
name = "Pavel Sapezhka"

